# Generated by Django 4.1.6 on 2023-03-03 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_featurevalue_options_alter_brand_image_name_and_more'),
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ درج سفارش')),
                ('update_date', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش سفارش')),
                ('is_finaly', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('order_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد تولیدی یرای سفارش')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='تخفیف روی سفارش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'db_table': 't_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت در فاکتور')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details1', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_details1', to='products.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': ' جزییات سفارش',
                'db_table': 't_Order_details',
            },
        ),
    ]
