# Generated by Django 4.1.6 on 2023-03-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_peymenttype_order_description_order_peyment_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peymenttype',
            table='t_peyment_types',
        ),
    ]
