# Generated by Django 4.1.6 on 2023-03-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_finally',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
    ]
